services:
  minio:
    image: quay.io/minio/minio
    networks:
      - app_network
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/${DATA_SUBDIR}/minio:/data
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    command:
      - server
      - /data
      - --console-address
      - ":9001"
  createbuckets:
    image: minio/mc
    networks:
      - app_network
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 ${S3_ACCESS_KEY} ${S3_SECRET_KEY};
      /usr/bin/mc rm -r --force myminio/${S3_BUCKET_NAME};
      /usr/bin/mc mb myminio/${S3_BUCKET_NAME};
      /usr/bin/mc policy download myminio/${S3_BUCKET_NAME};
      exit 0;
      "

networks:
  app_network:
    driver: bridge
